# Generated by Django 4.2.1 on 2023-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0007_alter_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newbuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('typehome', models.CharField(max_length=255)),
                ('square', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=255)),
            ],
        ),
    ]
