# Generated by Django 4.2.1 on 2023-05-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweetapp', '0008_newbuilding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('square', models.IntegerField(default=0)),
                ('room', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True)),
                ('address', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
